# This sample workflow execute 3 steps in sequence.
# 1) activity1, takes arg1 as input, and put result as result1.
# 2) it runs a parallel block which runs below sequence branches in parallel
#  2.1) sequence 1
#    2.1.1) activity2, takes result1 as input, and put result as result2
#    2.1.2) activity3, takes arg2 and result2 as input, and put result as result3
#  2.2) sequence 2
#    2.2.1) activity4, takes result1 as input, and put result as result4
#    2.2.2) activity5, takes arg3 and result4 as input, and put result as result5
# 3) activity1, takes result3 and result5 as input, and put result as result6.

variables:
  arg1: value1
  arg2: value2
  arg3: value3

root:
  sequence:
    elements:
      - activity:
         name: SampleActivity
         arguments:
           - arg1
         result: result1
         container_image: "ubuntu:24.10"
         commands:
          - dd if=/dev/zero of=/tmp/activity1.img bs=1M count=10
          - ls -la /tmp/activity1.img
          - echo "Argument1 $arg1"
      - parallel:
          branches:
            - sequence:
                elements:
                 - activity:
                    name: SampleActivity
                    arguments:
                      - result1
                    result: result2
                    commands:
                      - dd if=/dev/zero of=/tmp/activity2.img bs=1M count=10
                      - ls -la /tmp/activity2.img
                      - echo "Hello"
                 - activity:
                    name: SampleActivity
                    arguments:
                      - arg2
                      - result2
                    result: result3
            - sequence:
                elements:
                 - activity:
                    name: SampleActivity
                    arguments:
                      - result1
                    result: result4
                 - activity:
                    name: SampleActivity
                    arguments:
                      - arg3
                      - result4
                    result: result5
      - activity:
         name: SampleActivity
         arguments:
           - result3
           - result5
         result: result6
