// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/shell.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogStreamingService_Sh_FullMethodName   = "/logstream.LogStreamingService/Sh"
	LogStreamingService_Echo_FullMethodName = "/logstream.LogStreamingService/Echo"
)

// LogStreamingServiceClient is the client API for LogStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogStreamingService provides real-time streaming logs
type LogStreamingServiceClient interface {
	Sh(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error)
	Echo(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error)
}

type logStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogStreamingServiceClient(cc grpc.ClientConnInterface) LogStreamingServiceClient {
	return &logStreamingServiceClient{cc}
}

func (c *logStreamingServiceClient) Sh(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStreamingService_ServiceDesc.Streams[0], LogStreamingService_Sh_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamingService_ShClient = grpc.ServerStreamingClient[LogResponse]

func (c *logStreamingServiceClient) Echo(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogStreamingService_ServiceDesc.Streams[1], LogStreamingService_Echo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamingService_EchoClient = grpc.ServerStreamingClient[LogResponse]

// LogStreamingServiceServer is the server API for LogStreamingService service.
// All implementations must embed UnimplementedLogStreamingServiceServer
// for forward compatibility.
//
// LogStreamingService provides real-time streaming logs
type LogStreamingServiceServer interface {
	Sh(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error
	Echo(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error
	mustEmbedUnimplementedLogStreamingServiceServer()
}

// UnimplementedLogStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogStreamingServiceServer struct{}

func (UnimplementedLogStreamingServiceServer) Sh(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Sh not implemented")
}
func (UnimplementedLogStreamingServiceServer) Echo(*LogRequest, grpc.ServerStreamingServer[LogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedLogStreamingServiceServer) mustEmbedUnimplementedLogStreamingServiceServer() {}
func (UnimplementedLogStreamingServiceServer) testEmbeddedByValue()                             {}

// UnsafeLogStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogStreamingServiceServer will
// result in compilation errors.
type UnsafeLogStreamingServiceServer interface {
	mustEmbedUnimplementedLogStreamingServiceServer()
}

func RegisterLogStreamingServiceServer(s grpc.ServiceRegistrar, srv LogStreamingServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogStreamingService_ServiceDesc, srv)
}

func _LogStreamingService_Sh_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogStreamingServiceServer).Sh(m, &grpc.GenericServerStream[LogRequest, LogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamingService_ShServer = grpc.ServerStreamingServer[LogResponse]

func _LogStreamingService_Echo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogStreamingServiceServer).Echo(m, &grpc.GenericServerStream[LogRequest, LogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogStreamingService_EchoServer = grpc.ServerStreamingServer[LogResponse]

// LogStreamingService_ServiceDesc is the grpc.ServiceDesc for LogStreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogStreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logstream.LogStreamingService",
	HandlerType: (*LogStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sh",
			Handler:       _LogStreamingService_Sh_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Echo",
			Handler:       _LogStreamingService_Echo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/shell.proto",
}
